import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { applyOperation, cloneProject, createInitialProject, migrateProject, validateLayout, buildCirculationGraph, inspectFloor, projectMetrics, type Project, type ArchitectureOperation } from "../src/lib/architecture.ts";
import { createArchMorphTools } from "../src/lib/webmcp-tools.ts";
import { doorArcSweepFlag, doorSwingSign } from "../src/lib/door-geometry.ts";
import { presentationBounds } from "../src/lib/model-presentation.ts";
import { walkCollisionSegments, walkSurfaceContains } from "../src/lib/walk-navigation.ts";
import { resolveWalkPosition } from "../src/lib/spatial3d.ts";
import * as persistence from "../src/lib/persistence.ts";
const edit = (p: Project, op: ArchitectureOperation) => applyOperation(p, op, "human").project;
const fixture = migrateProject(JSON.parse(readFileSync(new URL("../fixtures/sukoon-family-retreat.archmorph.json", import.meta.url), "utf8")).project);
assert.ok(!validateLayout(fixture).issues.some(i => i.code === "UPPER_FLOOR_BASE_UNVERIFIED"), "Sukoon stair void is not an unsupported occupied slab");
const terrace = fixture.balconies.find(b => b.kind === "terrace")!;
const before = JSON.stringify(fixture);
assert.throws(() => edit(fixture,{ type: "add_balcony", ...terrace }), /overlaps/);
assert.equal(JSON.stringify(fixture),before);
const duplicated = cloneProject(fixture); duplicated.balconies.push({...terrace,id:"duplicate-terrace"});
assert.equal(projectMetrics(duplicated).projectTerraceArea,280,"duplicate imported outdoor area is counted once");
assert.ok(validateLayout(duplicated).issues.some(i => i.code === "INVALID_BALCONY"));
const circulation = buildCirculationGraph(fixture);
assert.equal(circulation.reachableRoomIds.length,27);
assert.equal(circulation.reachableOutdoorIds.length,2,"both terraces/balconies are circulation destinations");
const upperId = fixture.floors[1].id;
const upper = inspectFloor(fixture,upperId,"full");
assert.equal((upper.stairs as unknown[]).length,1,"full inspection includes the upper arrival stair");
const unsupported = {...fixture, openings: fixture.openings.filter(o => o.floorId === upperId), stairs: []};
assert.equal(buildCirculationGraph(unsupported).hasExteriorAccess,false,"an upper outdoor door cannot invent ground site access");
const entryId = circulation.mainEntranceOpeningId!;
for (const op of [{type:"update_opening",openingId:entryId,width:0.5},{type:"update_opening",openingId:entryId,height:2}] as ArchitectureOperation[]) assert.throws(() => edit(fixture,op),/Doors must/);
const tiny = cloneProject(fixture); tiny.openings.find(o => o.id===entryId)!.width=0.5;
assert.ok(validateLayout(tiny).issues.some(i=>i.code==="INVALID_OPENING"&&i.elementIds.includes(entryId)));
assert.ok(buildCirculationGraph(tiny).invalidDoorIds.includes(entryId));
const terrainEdge = resolveWalkPosition(terrace.x+0.05,terrace.y+5,0.38,walkCollisionSegments(fixture,upperId));
assert.ok(terrainEdge.x >= terrace.x+0.38,"terrace railing pushes a walker back onto the slab");
assert.equal(walkSurfaceContains(fixture,upperId,{x:3,y:55}),false,"no upper floor outside supported geometry");
assert.equal(walkSurfaceContains(fixture,"floor-ground",{x:3,y:55}),true,"ground site remains walkable");
assert.equal(walkSurfaceContains(fixture,upperId,{x:terrace.x+2,y:terrace.y+2}),true);

let project = edit(createInitialProject(),{type:"create_room",floorId:"floor-ground",name:"Room",roomType:"Custom",x:5,y:12,width:12,length:12});
const roomId=project.rooms[0].id;
const north = project.walls.find(w=>w.roomSides.some(s=>s.side==="north"))!;
project=edit(project,{type:"add_opening",kind:"door",wallId:north.id,offset:6,state:"closed",opensIntoRoomId:roomId});
const door=project.openings[0];
const porch = edit(project,{type:"add_balcony",floorId:"floor-ground",name:"Arrival porch",x:5,y:9,width:12,length:3});
assert.equal(buildCirculationGraph(porch).hasExteriorAccess,true,"a ground-level porch door remains a valid site entrance");
assert.equal(buildCirculationGraph(porch).reachableOutdoorIds.length,1);
const misplacedDoor = cloneProject(project); misplacedDoor.openings[0].offset = -1;
assert.ok(buildCirculationGraph(misplacedDoor).invalidDoorIds.includes(door.id),"an opening beyond its wall cannot imply a traversable route");
assert.equal(doorSwingSign(project,door),1,"north door explicitly opens inside, independent of legacy sign");
assert.equal(doorArcSweepFlag(project,{...door,hingeSide:"start"}),1);
assert.equal(doorArcSweepFlag(project,{...door,hingeSide:"end"}),0,"end hinge reverses the drawing arc direction");
assert.ok(walkCollisionSegments(project,"floor-ground").some(s => s.x1<=11 && s.x2>=11 && s.z1===12));
const opened=edit(project,{type:"update_opening",openingId:door.id,state:"open"});
assert.ok(!walkCollisionSegments(opened,"floor-ground").some(s => s.x1<11 && s.x2>11 && s.z1===12),"open door is traversable");
const response=applyOperation(opened,{type:"resize_room",roomId,width:13,length:12},"agent");
assert.deepEqual(response.result.room,response.project.rooms[0]);
for(const id of (response.result.room as {wallIds:string[]}).wallIds) assert.ok(response.project.walls.some(w=>w.id===id));
project=edit(project,{type:"add_wall",floorId:"floor-ground",x1:5,y1:13,x2:11,y2:13});
assert.ok(validateLayout(project).issues.some(i=>i.code==="DOOR_SWEEP_CLASH"),"explicit door sweeps detect a partition crossing the clearance");
let live=createInitialProject();
const tools=createArchMorphTools({getProject:()=>live,perform:operation=>{const out=applyOperation(live,operation,"agent");live=out.project;return out;},noteActivity:()=>{},captureSnapshot:async()=>({}),exportPlan:()=>({})});
const tool=(name:string)=>tools.find(t=>t.name===name)!;
const changes=[{tool:"create_room",input:{floorId:"floor-ground",name:"Batch room",roomType:"Custom",x:5,y:12,width:12,length:12}},{tool:"update_room",input:{roomId:"$1.room.id",name:"Reviewed room"}}];
const initial=JSON.stringify(live),version=live.version;
const preview=tool("preview_changes").execute({expectedVersion:version,changes}) as {changeCount:number};
assert.equal(preview.changeCount,2); assert.equal(JSON.stringify(live),initial,"preview does not mutate live state");
assert.throws(()=>tool("apply_changes").execute({expectedVersion:version,changes:[...changes,{tool:"resize_room",input:{roomId:"$1.room.id",width:1,length:12}}]}),/step 3/i);
assert.equal(JSON.stringify(live),initial,"failed batch rolls back all earlier steps");
const batchResult = tool("apply_changes").execute({expectedVersion:version,changes}) as {results:Record<string,unknown>[]};
assert.equal(live.version,version+1); assert.equal(live.rooms[0].name,"Reviewed room"); assert.equal(live.activity[0].operation,"apply_batch");
for (const result of batchResult.results) assert.equal(result.projectVersion,live.version,"batch steps report the one committed version");
assert.deepEqual(batchResult.results[0].room,live.rooms[0],"batch entity results use final committed topology and names");
const floorBounds = presentationBounds(live,"floor-ground");
assert.ok(floorBounds.max[0] < live.plot.width,"floor camera framing does not include the whole site boundary");
assert.throws(()=>tool("apply_changes").execute({expectedVersion:version,changes}),/changed/);
assert.throws(()=>tool("update_room").execute({roomId:live.rooms[0].id,roomType:"Imaginary"}),/one of/);
const focused=edit(live,{type:"focus_element",elementId:live.rooms[0].id});
assert.equal(edit(focused,{type:"set_camera",preset:"rear"}).view.focusElementId,undefined);
assert.equal(edit(focused,{type:"set_camera",preset:"rear",scope:"selection"}).view.focusElementId,live.rooms[0].id);
assert.equal(edit(focused,{type:"set_camera",preset:"rear",scope:"floor"}).view.focusElementId,"floor-ground");
const memory=new Map<string,string>(),sessionA=new Map<string,string>(),sessionB=new Map<string,string>();
const storage=(map:Map<string,string>)=>({getItem:(key:string)=>map.get(key)??null,setItem:(key:string,value:string)=>map.set(key,value)});
const mockWindow={localStorage:storage(memory),sessionStorage:storage(sessionA)};
Object.defineProperty(globalThis,"window",{configurable:true,value:mockWindow});
const savedA=await persistence.createNewLocalProject("Tab A");
mockWindow.sessionStorage=storage(sessionB);
const savedB=await persistence.createNewLocalProject("Tab B");
const changedB=edit(savedB,{type:"rename_project",name:"Edited B"});
await persistence.saveProjectLocally(changedB,savedB.revisionId,{past:[savedB],future:[]});
assert.equal(persistence.loadLatestProject()!.id,savedB.id);
mockWindow.sessionStorage=storage(sessionA);
assert.equal(persistence.loadLatestProject()!.id,savedA.id,"another tab's autosave never changes this tab's active home");
assert.equal(persistence.loadProjectHistory(savedB.id).past[0].name,"Tab B","Undo survives reload");
const savedAgain=await persistence.saveProjectLocally(persistence.loadSavedProject(savedB.id),undefined);
assert.equal(persistence.loadProjectHistory(savedAgain.id).past.length,1,"activity-only saves preserve history");
console.log("Audit fixes passed: actual Sukoon geometry, slab union and rejection, valid entrances/outdoor routes, stair inspection, wall IDs, door sweeps/states, terrace boundaries, atomic preview/apply, schema validation, camera scopes, durable Undo and per-tab active homes.");
